dist: trusty

language: c

compiler: gcc

notifications:
    slack: rdesktop:RZWCtYeVc9qVzsBvTzQtmyLt
    
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libpcsclite-dev libxcursor-dev libao-dev libasound2-dev

script: ./bootstrap && ./configure && make
